### ISSUE TITLE
Can I specify the language to transcribe, like Chinese?

### ISSUE THREAD

**Issue by CicoZhang** [Jaymon/transcribe#5]
Is there an parameter to specify language, like Chinese?

**Comment by CicoZhang** [comment]
I find this. `--language zh-CN`
https://github.com/Jaymon/transcribe/blob/5c431f320aae50bb67379f890001d330b0fb71dc/transcribe/__main__.py#L55

**Comment by Jaymon** [comment]
Glad you found the flag, you can see all the flags without looking at the code:

    $ transcribe speech --help

Or, if you are running from `master`:

    $ python3 -m transcribe speech --help
